### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by LordPandaIsHere** [cynecx/async-watch#2]
I would like to contact you. Please provide me with your info. Or add me on discord PandaLord#5413 @cynecx

**Comment by PandaLord69** [comment]
@cynecx

**Comment by PandaLord69** [comment]
@cynecx please contact iamthesandy@gmail.com.

**Comment by PandaLord69** [comment]
@cynecx i would like to hire you for a project please contact me

**Comment by PandaLord69** [comment]
@cynecx how do I contact you . I need work done. Are you msnduy or duyan. I worked with you on envy products long ago

**Comment by PandaLord69** [comment]
@cynecx iamthesandy@gmail.com email me. 150$ work I need please
